services:
  mongodb:
    image: 'mongo'
    container_name: mongodb
  backend:
    build: ./backend
    ports:
      - '80:80'
    container_name: movieflix-api
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    container_name: movieflix-react
    stdin_open: true
    tty: true
    depends_on:
      - backend
